services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: rpnmore
      POSTGRES_PASSWORD: rpnmore_secret
      POSTGRES_DB: rpnmore_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://rpnmore:rpnmore_secret@db:5432/rpnmore_db?schema=public
    depends_on:
      - db
    volumes:
      - ./public:/app/public:ro
      - ./backend/uploads:/app/backend/uploads
      - ./.env:/app/.env:ro

volumes:
  postgres_data:
